### PR TITLE
Fix for iframes and future timeout

### LINKED ISSUE #163: `<iframe>` elements stop page from loading
I am trying to visit a page that uses Google's RecaptchaV3. The issue I'm having is the following: for some reason, the equest sent by the `src` attribute of the `<iframe>` element gets stuck on pending, on the content download phase, causing `page.goto` to fail.

If, for any reason, the rust code panics and the browser survives as a zombie process, everything imediately goes back to normal, i.e. the request resolves as soon as Rust crashes.

Below are screenshots of the problem and a minimal reproduction of the code I'm using:
```rust
use std::{path::Path, time::Duration};

use chromiumoxide::{Browser, BrowserConfig, BrowserFetcher, BrowserFetcherOptions};
use futures::StreamExt;

#[tokio::main]
async fn main() {
    let download_path = Path::new("./download");
    let _ = std::fs::create_dir_all(download_path);

    let fetcher_config = BrowserFetcherOptions::builder()
        .with_path(download_path)
        .build()
        .unwrap();

    let fetcher = BrowserFetcher::new(fetcher_config);

    let info = fetcher.fetch().await.unwrap();

    let config = BrowserConfig::builder()
        .chrome_executable(info.executable_path)
        .launch_timeout(std::time::Duration::from_secs(20))
        .with_head()
        .arg("--lang=en_US")
        .no_sandbox()
        .build()
        .unwrap();

    let (mut browser, mut handler) = Browser::launch(config).await.unwrap();

    let handle = tokio::spawn(async move {
        while let Some(h) = handler.next().await {
            if h.is_err() {
                break;
            }
        }
    });

    browser
        .new_page("https://esaj.tjms.jus.br/cpopg5/open.do")
        .await
        .unwrap();

    tokio::time::sleep(Duration::from_secs(50)).await;

    browser.close().await.unwrap();
    browser.wait().await.unwrap();
    handle.await.unwrap();
}
```

The weird thing about it is that it does have a 200 HTTP status code, even though it's still pending
image

### LINKED ISSUE #171: CommandFuture will be polled forever if Page is closed.
**Step's to reproduce:**
Connect or create browser, use page.goto({long-loading-url}),
and just close the tab in browser while page is still loading.
Since there is no shutdown process for destroyed targets, then we will have future that will run's forever.

**Current behaviour:**
Code will run forever.

**Expected behaviour:**
Receive a timeout error and future requests should be dropped since target page does not exists anymore.

### PR DESCRIPTION
**Pull request by chirok11**
This library have some problems with handling iframes and dont work properly and handle service workers.
I created this pull request that contain's fixes for few cases.

1) Some websites, that contain's an iframe will load forever and never resolve's.
Problem is: I checked puppeteer or playwright libraries, and found, that they're sending runIfWaitingForDebugger for attached targets to target, what chromiumoxide doesn't do or handle.
Also, I noticed, that we have to send two events for service workers, runIfWaitingForDebugger and detachFromTarget.
I implemented both, and page's, that won't load before now loading successfully.
Example URLs: 
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe
https://www.financialexpress.com/ (has an service worker)

Solution: I added runIfWaitingForDebugger when CdpEvent::TargetAttachedToTarget is emitted, and also, if it new target is service_worker, then we also send event detachFromTarget

After, I noticed, that page's now loading correctly, but future .goto(url) still failing on timeout. Then I started discovery source of this problem. And solution is in next case.

2) If page has an iframe, it will load forever and `.goto(url)` always fail on timeout.
Sample URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe
Expected behaviour: Page loaded and `.goto(url)` future returns Ok.

Solution: I modified check_lifecycle and checking it for if lifecycle events contain's "load" event, or (if page url is None and lifecycle events has event DOMContentLoaded).

3) No way to customize request timeout. 
Solution: I added function connect_with_config to Browser instance. It accepts url as first parameter, and HandlerConfig as second.

4) Problem with .goto(url) action.
How to reproduce: Open new page and call .goto(url) on it, then go to browser and close tab (you should choose long-loading website to reproduce).
Future never will be await'ed, even there will be no timeout or other error.
So it will runs forever.

Solution: Added DelayFuture in CommandFuture, it uses crate::REQUEST_TIMEOUT and will return CdpError::Timeout if timer is ready.

Closes #163 and closes #171

### CODE REVIEW

**Comment by escritorio-gustavo** [comment]
This PR will fix #163

File: src/handler/target.rs [hunk 1]
```diff
@@ -246,6 +249,34 @@ impl Target {
...
+
+                match ev.target_info.r#type.as_ref() {
+                    "service_worker" => {
+                        let detach_command = DetachFromTargetParams::builder()
+                            .session_id(ev.session_id.clone())
+                            .build();
+
+                        self.queued_events.push_back(TargetEvent::Request(Request {
+                            method: detach_command.identifier(),
+                            session_id: Some(self.session_id.clone().take().unwrap().into()),
```
Comment (mattsse) [inline src/handler/target.rs:272]: I'd rather have a `.map(Into::into)` here and no unwrap

File: src/handler/commandfuture.rs [hunk 2]
```diff
@@ -20,6 +20,8 @@ pin_project! {
         rx_command: oneshot::Receiver<M>,
         #[pin]
         target_sender: mpsc::Sender<TargetMessage>,
+        #[pin]
```
Comment (mattsse) [inline src/handler/commandfuture.rs:23]: can we add a oneline doc why we're using this

**Review by mattsse — CHANGES_REQUESTED** [review]
tysm for looking into this.

not familiar with these settings, but all of this sounds reasonable.
smol nit, otherwise lgtm

File: src/handler/commandfuture.rs (hunk 2 above)
Comment (chirok11) [reply src/handler/commandfuture.rs:23]: Otherwise we would not be possible to call .poll on this DelayFuture, #[pin] allows us to do that.
Or I didn't found the correct way to do that.

**Comment by chirok11** [comment]
I am not quite familiar with github workflow with pull's or issues, I pushed new commit to my branch, should I reopen pull request or how?

File: src/handler/commandfuture.rs [hunk 3]
```diff
@@ -42,10 +47,15 @@ impl<T: Command> CommandFuture<T> {
             cmd, tx, session,
         )?));
 
+        let delay = futures_timer::Delay::new(std::time::Duration::from_millis(
+            crate::handler::REQUEST_TIMEOUT,
+        ));
```
Comment (mattsse) [inline src/handler/commandfuture.rs:52]: 30s should be sufficient for any command, so this seems reasonable to me
